// Generated by scripts/gen-asset-manifest.mjs — do not edit by hand.
// Rewritten automatically when the dev server starts, when art is added or
// removed while it is running, and at the start of every build.

export const assetManifest = {
  icons: ['anvilIcon', 'BookIcon', 'chartIcon', 'chestIcon', 'deckIcon', 'expIcon', 'heartIcon', 'keyIcon', 'moneyIcon', 'totemIcon', 'trashcanIcon'],
  shop: ['keeper', 'smith'],
  spells: ['dark', 'earth', 'fire', 'light', 'water', 'wind'],
  totems: ['Dolbae', 'Magic_Parasite_Zoah', 'parasite_hunter_Yaharl', 'Silver Knight', 'TheExplorer', 'Thirthteeth_Knight'],
  ui: ['awaken', 'cover', 'title'],
} as const

/**
 * The filename behind each key, keyed "category/key". Art may be any
 * supported format and any capitalisation, so the name is recorded rather
 * than reconstructed from the key.
 */
export const assetFiles: Readonly<Record<string, string>> = {
  "icons/anvilIcon": "anvilIcon.webp",
  "icons/BookIcon": "BookIcon.webp",
  "icons/chartIcon": "chartIcon.webp",
  "icons/chestIcon": "chestIcon.webp",
  "icons/deckIcon": "deckIcon.webp",
  "icons/expIcon": "expIcon.webp",
  "icons/heartIcon": "heartIcon.webp",
  "icons/keyIcon": "keyIcon.webp",
  "icons/moneyIcon": "moneyIcon.webp",
  "icons/totemIcon": "totemIcon.webp",
  "icons/trashcanIcon": "trashcanIcon.webp",
  "shop/keeper": "keeper.webp",
  "shop/smith": "smith.webp",
  "spells/dark": "dark.webp",
  "spells/earth": "earth.webp",
  "spells/fire": "fire.webp",
  "spells/light": "light.webp",
  "spells/water": "water.webp",
  "spells/wind": "wind.webp",
  "totems/Dolbae": "Dolbae.webp",
  "totems/Magic_Parasite_Zoah": "Magic_Parasite_Zoah.webp",
  "totems/parasite_hunter_Yaharl": "parasite_hunter_Yaharl.webp",
  "totems/Silver Knight": "Silver Knight.webp",
  "totems/TheExplorer": "TheExplorer.webp",
  "totems/Thirthteeth_Knight": "Thirthteeth_Knight.webp",
  "ui/awaken": "awaken.webp",
  "ui/cover": "cover.webp",
  "ui/title": "title.webp"
}
