// Generated by scripts/gen-audio-manifest.mjs — do not edit by hand.
// Rewritten when the dev server starts, when audio is added or removed while
// it runs, and at the start of every build.

/** Cue names that have a file behind them, by folder. */
export const audioManifest = {
  music: ["battle","boss","dungeon","menu","rest","results"],
  ambient: ["drip","night","wind"],
  sfx: ["battleStart","bossDoor","cancel","chestOpen","confirm","correct","damage","defeat","diceRoll","discovery","enemyAppear","enemyAttack","gameChoice","gameStart","itemUse","levelUp","move","npcTalk","playerAttack","reward","shrine","trapTrigger","victory","wrong"],
} as const

/**
 * Music a world ships for itself, by world id. A slot listed here overrides
 * the global track of the same name for runs in that world.
 */
export const worldMusic: Readonly<Record<string, readonly string[]>> = {}

/**
 * Alternates for a music slot, by slot name. A run picks one of these when it
 * starts and keeps it until the next run, so a dungeon sounds the same all
 * the way through and different the next time.
 */
export const musicPools: Readonly<Record<string, readonly string[]>> = {"dungeon":["dungeon/Masashi Hamauzu - Topic - DG”sadness”","dungeon/Masashi Hamauzu - Topic - 大いなる目的へ"]}

/**
 * The file behind each cue, keyed by its path from public/. Cue names are
 * fixed; the file may be any format the browser decodes and any
 * capitalisation, so the name is recorded rather than reconstructed.
 */
export const audioFiles: Readonly<Record<string, string>> = {
  "audio/music/battle": "battle.mp3",
  "audio/music/boss": "boss.mp3",
  "audio/music/dungeon": "dungeon.mp3",
  "audio/music/menu": "menu.mp3",
  "audio/music/rest": "rest.mp3",
  "audio/music/results": "results.mp3",
  "audio/ambient/drip": "drip.mp3",
  "audio/ambient/night": "night.mp3",
  "audio/ambient/wind": "wind.mp3",
  "audio/sfx/battleStart": "battleStart.mp3",
  "audio/sfx/bossDoor": "bossDoor.mp3",
  "audio/sfx/cancel": "cancel.mp3",
  "audio/sfx/chestOpen": "chestOpen.mp3",
  "audio/sfx/confirm": "confirm.mp3",
  "audio/sfx/correct": "correct.mp3",
  "audio/sfx/damage": "damage.mp3",
  "audio/sfx/defeat": "defeat.mp3",
  "audio/sfx/diceRoll": "diceRoll.mp3",
  "audio/sfx/discovery": "discovery.mp3",
  "audio/sfx/enemyAppear": "enemyAppear.mp3",
  "audio/sfx/enemyAttack": "enemyAttack.mp3",
  "audio/sfx/gameChoice": "gameChoice.mp3",
  "audio/sfx/gameStart": "gameStart.mp3",
  "audio/sfx/itemUse": "itemUse.mp3",
  "audio/sfx/levelUp": "levelUp.mp3",
  "audio/sfx/move": "move.mp3",
  "audio/sfx/npcTalk": "npcTalk.mp3",
  "audio/sfx/playerAttack": "playerAttack.mp3",
  "audio/sfx/reward": "reward.mp3",
  "audio/sfx/shrine": "shrine.mp3",
  "audio/sfx/trapTrigger": "trapTrigger.mp3",
  "audio/sfx/victory": "victory.mp3",
  "audio/sfx/wrong": "wrong.mp3",
  "audio/music/dungeon/Masashi Hamauzu - Topic - DG”sadness”": "dungeon/Masashi Hamauzu - Topic - DG”sadness”.mp3",
  "audio/music/dungeon/Masashi Hamauzu - Topic - 大いなる目的へ": "dungeon/Masashi Hamauzu - Topic - 大いなる目的へ.mp3"
}
