// Generated by scripts/gen-world-manifest.mjs — do not edit by hand.
// Rewritten when the dev server starts, when art under public/worlds is
// added or removed while it runs, and at the start of every build.

export interface WorldPack {
  id: string
  name: string
  description: string
  /** False when a required slot is missing; such a world is never offered. */
  complete: boolean
  /** Exactly what is missing, for the report shown to whoever is building it. */
  missing: readonly string[]
  locations: readonly string[]
  optionalLocations: readonly string[]
  events: readonly string[]
  npcs: readonly string[]
  enemies: readonly string[]
  bosses: readonly string[]
  /**
   * The filename behind each slot, keyed "folder/slot". Slot names are fixed
   * and lower-camel; the file may be any supported format and any
   * capitalisation, so the name is recorded rather than reconstructed.
   */
  files: Readonly<Record<string, string>>
}

export const requiredLocations = ["entrance","corridor1","corridor2","keyRoom","restRoom","pathwayFork","shrineRoom","treasureRoom","trapRoom","bossRoom"] as const
export const requiredEvents = ["bossDoor","roadSign","key","trap1","trap2","treasureLocked","treasureOpened","treasureMimic","rest","shrineDoor"] as const
export const minNpcs = 3
export const minEnemies = 3

export const worldPacks: readonly WorldPack[] = [
  {
    id: "dragon-king-palace",
    name: "용왕의 던전",
    description: "물에 잠긴 회랑과 금빛 보고. 깊은 곳에서 무언가가 기다립니다.",
    complete: true,
    missing: [],
    locations: ["battle2","bossRoom","corridor1","corridor2","entrance","keyRoom","pathwayFork","restRoom","shrineRoom","trapRoom","treasureRoom"],
    optionalLocations: ["battle2"],
    events: ["bossDoor","key","rest","roadSign","shrineDoor","trap1","trap2","treasureLocked","treasureMimic","treasureOpened"],
    npcs: ["hunter","merchant","pilgrim","scholar","wanderer"],
    enemies: ["DragonGuard","goblin","slime"],
    bosses: ["DragonKingSpirit","minotaur","waterDragonRyu"],
    files: {"locations/battle2":"battle2.webp","locations/bossRoom":"bossRoom.webp","locations/corridor1":"corridor1.webp","locations/corridor2":"corridor2.webp","locations/entrance":"entrance.webp","locations/keyRoom":"keyRoom.webp","locations/pathwayFork":"pathwayFork.webp","locations/restRoom":"restRoom.webp","locations/shrineRoom":"shrineRoom.webp","locations/trapRoom":"trapRoom.webp","locations/treasureRoom":"treasureRoom.webp","events/bossDoor":"bossDoor.webp","events/key":"key.webp","events/rest":"rest.webp","events/roadSign":"roadSign.webp","events/shrineDoor":"shrineDoor.webp","events/trap1":"trap1.webp","events/trap2":"trap2.webp","events/treasureLocked":"treasureLocked.webp","events/treasureMimic":"treasureMimic.webp","events/treasureOpened":"treasureOpened.webp","npcs/hunter":"hunter.png","npcs/merchant":"merchant.png","npcs/pilgrim":"pilgrim.webp","npcs/scholar":"scholar.webp","npcs/wanderer":"wanderer.webp","enemies/DragonGuard":"DragonGuard.webp","enemies/goblin":"goblin.webp","enemies/slime":"slime.webp","bosses/DragonKingSpirit":"DragonKingSpirit.webp","bosses/minotaur":"minotaur.webp","bosses/waterDragonRyu":"waterDragonRyu.webp"},
  },
  {
    id: "parasite-garden",
    name: "기생의 정원",
    description: "빛이 드는 폐허를 덩굴과 이빨이 뒤덮었습니다. 자라나는 것들이 지켜보고 있습니다.",
    complete: true,
    missing: [],
    locations: ["battle1","battle2","bossRoom","corridor1","corridor2","corridor3","entrance","keyRoom","pathwayFork","restRoom","restRoom2","shrineRoom","trapRoom","treasureRoom"],
    optionalLocations: ["battle1","battle2","corridor3"],
    events: ["bossDoor","key","rest","roadSign","shrineDoor","trap1","trap2","treasureLocked","treasureMimic","treasureOpened"],
    npcs: ["hunter","merchant","pilgrim","scholar","wanderer"],
    enemies: ["Armatick","Man-Eater","Pseudoroid","Scalatick Runt"],
    bosses: ["Zoah Awakend"],
    files: {"locations/battle1":"battle1.webp","locations/battle2":"battle2.webp","locations/bossRoom":"bossRoom.webp","locations/corridor1":"corridor1.webp","locations/corridor2":"corridor2.webp","locations/corridor3":"corridor3.webp","locations/entrance":"entrance.webp","locations/keyRoom":"keyRoom.webp","locations/pathwayFork":"pathwayFork.webp","locations/restRoom":"restRoom.webp","locations/restRoom2":"restRoom2.webp","locations/shrineRoom":"shrineRoom.webp","locations/trapRoom":"trapRoom.webp","locations/treasureRoom":"treasureRoom.webp","events/bossDoor":"bossDoor.webp","events/key":"Key.webp","events/rest":"rest.webp","events/roadSign":"roadSign.webp","events/shrineDoor":"shrineDoor.webp","events/trap1":"trap1.webp","events/trap2":"trap2.webp","events/treasureLocked":"treasureLocked.webp","events/treasureMimic":"treasureMimic.webp","events/treasureOpened":"treasureOpened.webp","npcs/hunter":"hunter.png","npcs/merchant":"merchant.png","npcs/pilgrim":"pilgrim.webp","npcs/scholar":"scholar.webp","npcs/wanderer":"wanderer.webp","enemies/Armatick":"Armatick.webp","enemies/Man-Eater":"Man-Eater.webp","enemies/Pseudoroid":"Pseudoroid.webp","enemies/Scalatick Runt":"Scalatick Runt.webp","bosses/Zoah Awakend":"Zoah Awakend.webp"},
  },
  {
    id: "profane-prison",
    name: "불경한 감옥",
    description: "사슬에 매달린 철창과 금빛 봉인이 새겨진 돌. 이곳에 갇힌 것은 죄수만이 아닙니다.",
    complete: true,
    missing: [],
    locations: ["battle1","bossRoom","corridor1","corridor2","corridor3","corridor4","entrance","keyRoom","pathwayFork","restRoom","shrineRoom","trapRoom","treasureRoom"],
    optionalLocations: ["battle1","corridor3","corridor4"],
    events: ["bossDoor","key","rest","roadSign","shrineDoor","trap1","trap2","treasureLocked","treasureMimic","treasureOpened"],
    npcs: ["hunter","merchant","pilgrim","scholar","wanderer"],
    enemies: ["The Bouncer","The Sniper","The Watcher"],
    bosses: ["Eshra The Profane"],
    files: {"locations/battle1":"battle1.webp","locations/bossRoom":"bossRoom.webp","locations/corridor1":"corridor1.webp","locations/corridor2":"corridor2.webp","locations/corridor3":"corridor3.webp","locations/corridor4":"corridor4.webp","locations/entrance":"entrance.webp","locations/keyRoom":"keyRoom.webp","locations/pathwayFork":"pathwayFork.webp","locations/restRoom":"restRoom.webp","locations/shrineRoom":"shrineRoom.webp","locations/trapRoom":"trapRoom.webp","locations/treasureRoom":"treasureRoom.webp","events/bossDoor":"bossDoor.webp","events/key":"Key.webp","events/rest":"rest.webp","events/roadSign":"roadSign.webp","events/shrineDoor":"shrineDoor.webp","events/trap1":"trap1.webp","events/trap2":"trap2.webp","events/treasureLocked":"treasureLocked.webp","events/treasureMimic":"treasureMimic.webp","events/treasureOpened":"treasureOpened.webp","npcs/hunter":"hunter.png","npcs/merchant":"merchant.png","npcs/pilgrim":"pilgrim.webp","npcs/scholar":"scholar.webp","npcs/wanderer":"wanderer.webp","enemies/The Bouncer":"The Bouncer.webp","enemies/The Sniper":"The Sniper.webp","enemies/The Watcher":"The Watcher.webp","bosses/Eshra The Profane":"Eshra The Profane.webp"},
  },
  {
    id: "starter",
    name: "첫 번째 길",
    description: "조용한 연습용 던전. 아직 그려지지 않은 세계입니다.",
    complete: true,
    missing: [],
    locations: ["bossRoom","corridor1","corridor2","entrance","keyRoom","pathwayFork","restRoom","shrineRoom","trapRoom","treasureRoom"],
    optionalLocations: [],
    events: ["bossDoor","key","rest","roadSign","shrineDoor","trap1","trap2","treasureLocked","treasureMimic","treasureOpened"],
    npcs: ["merchant","scholar","wanderer"],
    enemies: ["brute","crawler","prowler","shade"],
    bosses: ["guardian"],
    files: {"locations/bossRoom":"bossRoom.webp","locations/corridor1":"corridor1.webp","locations/corridor2":"corridor2.webp","locations/entrance":"entrance.webp","locations/keyRoom":"keyRoom.webp","locations/pathwayFork":"pathwayFork.webp","locations/restRoom":"restRoom.webp","locations/shrineRoom":"shrineRoom.webp","locations/trapRoom":"trapRoom.webp","locations/treasureRoom":"treasureRoom.webp","events/bossDoor":"bossDoor.webp","events/key":"key.webp","events/rest":"rest.webp","events/roadSign":"roadSign.webp","events/shrineDoor":"shrineDoor.webp","events/trap1":"trap1.webp","events/trap2":"trap2.webp","events/treasureLocked":"treasureLocked.webp","events/treasureMimic":"treasureMimic.webp","events/treasureOpened":"treasureOpened.webp","npcs/merchant":"merchant.png","npcs/scholar":"scholar.png","npcs/wanderer":"wanderer.webp","enemies/brute":"brute.webp","enemies/crawler":"crawler.webp","enemies/prowler":"prowler.webp","enemies/shade":"shade.webp","bosses/guardian":"guardian.webp"},
  },
]
